// login.js:
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const UPDATE = 'UPDATE';
export const SET_MESSAGE_LOGIN = 'SET_MESSAGE_LOGIN';
export const SET_MESSAGE_AREA_CLIENTE = 'SET_MESSAGE_AREA_CLIENTE';
export const SET_MESSAGE_CADASTRO = 'SET_MESSAGE_CADASTRO';
export const ERASE_ALL_MESSAGES = 'ERASE_ALL_MESSAGES';

// global.JS
export const TOGGLE_SIDEDRAWER = 'TOGGLE_SIDEDRAWER';
export const HIDE_SIDEDRAWER = 'HIDE_SIDEDRAWER';
